version: "3.8"

volumes:
  nextcloud:
  db:
  certbot:

services:
  nginx:
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - pdf
      - collabora
      - nextcloudApp
    links:
      - pdf
      - collabora
      - nextcloudApp
    expose:
      - 8081
      - 8082
      - 8083

  pdf:
    image: frooodle/s-pdf

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloudApp:
    image: nextcloud
    restart: always
    links:
      - db
      - collabora
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  collabora:
    image: collabora/code
    environment:
      - extra_params=--o:ssl.enable=false

  certbot:
    image: certbot/certbot
    volumes:
      - certbot:/etc/letsencrypt
